---
kind: pipeline
type: docker
name: generic

steps:
  - name: generic
    image: ghcr.io/nextcloud/continuous-integration-android8:3
    commands:
      - ./gradlew --console=plain assembleGeneric

trigger:
  branch:
    - master
    - stable-*
  event:
    - pull_request
    - push

---
kind: pipeline
type: docker
name: gplay

steps:
  - name: gplay
    image: ghcr.io/nextcloud/continuous-integration-android8:3
    commands:
      - ./gradlew --console=plain assembleGplay

trigger:
  branch:
    - master
    - stable-*
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: tests

steps:
  - name: all
    image: ghcr.io/nextcloud/continuous-integration-android8:3
    privileged: true
    commands:
      - emulator -avd android -no-snapshot -gpu swiftshader_indirect -no-window -no-audio -skin 500x833 &
      - scripts/wait_for_emulator.sh
      - ./gradlew --console=plain testGplayDebugUnitTest connectedGplayDebugAndroidTest

services:
  - name: server
    image: nextcloudci/server:server-17
    environment:
      EVAL: "true"
    commands:
      - BRANCH='stable23' /usr/local/bin/initnc.sh
      - echo 127.0.0.1 server >> /etc/hosts
      - su www-data -c "OC_PASS=user1 php /var/www/html/occ user:add --password-from-env --display-name='User One' user1"
      - su www-data -c "OC_PASS=user2 php /var/www/html/occ user:add --password-from-env --display-name='User Two' user2"
      - su www-data -c "OC_PASS=user3 php /var/www/html/occ user:add --password-from-env --display-name='User Three' user3"
      - su www-data -c "php /var/www/html/occ user:setting user2 files quota 1G"
      - su www-data -c "php /var/www/html/occ group:add users"
      - su www-data -c "php /var/www/html/occ group:adduser users user1"
      - su www-data -c "php /var/www/html/occ group:adduser users user2"
      - su www-data -c "git clone -b stable23 https://github.com/nextcloud/spreed.git /var/www/html/apps/spreed/"
      - su www-data -c "php /var/www/html/occ app:enable spreed"
      - /usr/local/bin/run.sh

trigger:
  branch:
    - master
    - stable-*
  event:
    - push
    - pull_request
---
kind: signature
hmac: ec6ade108f26cc1bcea307175de8389beb3e0d04be737e27b25e7de3effc2c32
