# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: "Assemble"

on:
  pull_request:
    branches: [ master, stable-* ]

# Declare default permissions as read only.
permissions: read-all

concurrency:
  group: assemble-flavors-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  flavor:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavor: [ Generic, Gplay ]
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: set up JDK 17
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: "temurin"
          java-version: 17

      - name: Gradle validate
        uses: gradle/actions/wrapper-validation@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3

      - name: Build ${{ matrix.flavor }}
        run: |
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> gradle.properties
          ./gradlew assemble${{ matrix.flavor }}

      - name: Archive apk
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ always() }}
        with:
          name: Nextcloud-${{ matrix.flavor }}-APK
          path: app/build/outputs/apk/**/**/*.apk
          retention-days: 5
