name: Unit tests

on:
    pull_request:
        branches: [ master, main, stable-* ]
    push:
        branches: [ master, main, stable-* ]

permissions:
    contents: read
    pull-requests: write

concurrency: 
    group: unit-tests-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            -   name: Set up JDK 17
                uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
                with:
                    distribution: "temurin"
                    java-version: 17
            -   name: Run unit tests with coverage
                uses: gradle/gradle-build-action@87a9a15658c426a54dd469d4fc7dc1a73ca9d4a6 # v2.10.0
                with:
                    arguments: testGplayDebugUnit
            -   name: Upload test artifacts
                if: ${{ failure() }}
                uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
                with:
                    name: test-results
                    path: app/build/reports/tests/testGplayDebugUnitTest/
